apiVersion: v1
kind: Service
metadata:
  name: kube-demo-service
spec:
  selector:
    app: kube-demo
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8880
      targetPort: 8880
      name: api-service
    - protocol: TCP
      port: 8885
      targetPort: 8885
      name: rpc-service